### ISSUE TITLE
Alternative Deploy Options?

### ISSUE THREAD

**Issue by jlaura** [stac-utils/stac-server#102]
First, many thanks to the devs and contributors on this project. It is awesome to see a cloud native stap-api implementation!

I am testing out both this project and stac-fastapi to see what might work better for our project. We are USGS center, like EROS, but for planetary data. 

It looks like, in our permissions environment on AWS, it is not possible use the serverless deploy (we lack the ability to set s3 bucket policies). It looks like I could hand deploy this project to AWS, but I worry a lot about being able to stay in sync. It is my hope to use/contirbute to the CQL work that is going to be happening in the future.

I wonder if anyone else is running this project not using the serverless file or if anyone else is in a similar environment and has thoughts about a way to get this project deploying using roles / IAM users.

If this is sufficiently off topic, please close. I realize this is not directly related to the code base, but rather to deploying the code base into an environment.

**Comment by demiurg** [comment]
One of the tickets is to start using CDK, but I wonder if that does or does not require some other permission you might not have. Have you tried AWS CDK in your environment?

**Comment by jlaura** [comment]
@demiurg Thanks for the info. I tested the AWS CDK using the AWS tutorial and am seeing issues identical to the serverless deploy. 

```
3:30:34 PM | CREATE_FAILED        | AWS::S3::BucketPolicy | StagingBucketPolicy
API: s3:PutBucketPolicy Access Denied

3:30:41 PM | DELETE_FAILED        | AWS::S3::BucketPolicy | StagingBucketPolicy
API: s3:DeleteBucketPolicy Access Denied
```

I am going to continue working this on my side as well. I believe someone else at USGS was looking to deploy (from EROS perhaps), so I will try to follow up in that direction as well.

☹️ that the deploy is a challenge due to permission issues (outside of this project's control entirely!)

**Comment by matthewhanson** [comment]
@jlaura it seems like you might have a workaround here?

The issue is that serverless always creates a deploy bucket first to be able to store artifacts. However, you should be able to specify an existing bucket to use as a deploy bucket.   Is this being deployed to CHS?   (which is where Eros is deploying to)

**Comment by jlaura** [comment]
@matthewhanson I don't have a workaround at this time, so any info would be amazing! This is deploying to CHS so should be inline with what EROS is doing. Really naive question that I am very to happy to get a one liner link to docs response - how do I deploy to an existing deploy bucket?

**Comment by matthewhanson** [comment]
So if you can create your own bucket (or have someone else do it) then in the serveless.yml file in the provider section use:

```
provider:
    deploymentBucket: <bucket name>
```

Don't worry about getting out of "sync", because it's just your serverless.yml file which is meant to be customized per deployment. Really what we should do is change the `serverless.yml` here in this repo to be `serverless-example.yml`.

**Comment by jlaura** [comment]
One more question, again related to my specific install. Very happy to take this to email as well so I do not clutter the issues here.

I am able to get the deploy working. Now I need to get the IAM user and permissions boundaries setup.

In the provider section I am defining:

```
  iam:
    role: arn:aws:sts::<acct#>:assumed-role/<role-group>/<uname>
    rolePermissionsBoundary: arn:aws:iam::<acct#>:policy/<custom-Permissions-Boundary>
```

From the Serverless docs, this should be setting the role and role permissions boundary for every lambda that is defined in the serverless.yml. 

It also looks like I need to define the permissions boundary in the resources as well a la:

```
  Resources:
    IamRoleCustomResourcesLambdaExecution:
      Type: 'AWS::IAM::Role'
      Properties:
        PermissionsBoundary: arn:aws:iam::<acct#>:policy/<boundary>
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
```

Unfortunately, deploys are failing with:

`API: iam:CreateRole User: arn:aws:sts::<acct#>:assumed-role/<group>/<uname> is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::<acct#>:role/stac-server-dev-us-west-2-lambdaRole

The good news it that serverless is attempting to use the defined IAM (:+1:). I am not sure though why the deploy is still attempting to create a role on the lambda funcs. I also tried defining a role for each function (to an existing role using the ARN). Still no joy.

It does seem like this is inches away from a successful deploy!

**Comment by jlaura** [comment]
I have been able to successfully deploy into my organizational environment using pre-existing / configured roles, modifying the access policy for ES via the UI, and using an existing bucket.

I much appreciate all the assistance!
