### ISSUE TITLE
Paging past 10k items

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#111]
Paging past 10k items throws a meaningless (to users) error: `search_phase_execution_exception`

### up to 10k items
https://earth-search.aws.element84.com/v0/search?limit=100&page=100

### past 10k items
https://earth-search.aws.element84.com/v0/search?limit=100&page=101

This limit can be changed:
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window

or `search_after` can be used which would change how pagination worked in stac-server:
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after

Even if the limit were raised (which will consume more memory and may be less performance, performance testing would be required) there will still be a limit, only higher, so at the very least `stac-server` should throw a meaningful error message when trying to page past 10k items.

**Comment by banesullivan** [comment]
Is there any plan to use `search_after` so that stac-server can properly handle deep pages?

**Comment by matthewhanson** [comment]
It hasn't been determined yet, but likely yes as it keeps coming up. Don't have an ETA on this though.

The next version of pystac-client, which will come in Q1 of 2022 will allow for splitting up searches and making async requests, so that would be another way, and perhaps better way, to get around this limit.

**Comment by philvarner** [comment]
search_after with a stable sort like created ascending is the preferred way to do this. 

One note is that ES uses milliseconds since the epoch for the search_after value for datatime fields, so a next value that would be guaranteed to be stable would be like: 

```
?next={created_ms_since_epoch},{itemId},{collection}
```
