### ISSUE TITLE
Implement support for Transaction Extension

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#115]
Add support for all transaction endpoints https://github.com/radiantearth/stac-api-spec/tree/master/ogcapi-features/extensions/transaction

Currently, only PATCH is supported (and broken per #42 

| Path                                                   | Content-Type Header | Description                                                                                                                      |
| ------------------------------------------------------ | ------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| `POST /collections/{collectionID}/items`               | `application/json`  | Adds a new item to a collection.                                                                                                 |
| `PUT /collections/{collectionId}/items/{featureId}`    | `application/json`  | Updates an existing item by ID using a complete item description.                                                                |
| `PATCH /collections/{collectionId}/items/{featureId}`  | `application/json`  | Updates an existing item by ID using a partial item description, compliant with [RFC 7386](https://tools.ietf.org/html/rfc7386). |
| `DELETE /collections/{collectionID}/items/{featureId}` | n/a                 | Deletes an existing item by ID.

**Comment by marchuffnagle** [comment]
Let's hold off on this until #92 is merged.
