### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by marchuffnagle** [stac-utils/stac-server#132]
The package.json file says that the license is "MIT", but the LICENSE file says "Copyright (c) 2016 Development Seed". What is the correct license?

**Comment by philvarner** [comment]
https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-do-i-handle-the-at

**Comment by marchuffnagle** [comment]
Today I learned more about the MIT license. Thanks for the info.

**Comment by philvarner** [comment]
Sorry, I didn't mean that to indicate we shouldn't do anything. I think we also need to add E84 to that as an additional copyright holder.
