### ISSUE TITLE
invalid geojson geometry for intersects should return a 400 rather than a 500

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-server#245]
This was a result of removing the geojson-validation library. Now, the intersects parameter is only validated to be valid JSON, rather than valid GeoJSON. The GeoJSON validation is done in ES, which will return a 500 error if there's a problem with the query.

Best option is not to reply on any of the deprecated libraries and instead just to a JSON schema validation https://geojson.org/schema/GeoJSON.json

**Comment by MattBialas** [comment]
This has been fixed in the PR above
