### ISSUE TITLE
Add link and version of stac-server

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#254]
It would be useful if the landing page had a link to stac-server and also indicated the version in some way.  Right now there's a `docs` link that points to the documentation of stac-server, but not sure `docs` is the right term here, it's not really descriptive about what this is.

So a better rel type.... "server", "software"?
For version maybe the link should be the full path to the commit or tag?

**Comment by ircwaves** [comment]
🥈 --> adding the `stac_api_spec` would be an informative piece to add.  It would allow communication to the client of which version of the spec the deployment is adherent.

**Comment by matthewhanson** [comment]
The version actually is in the conformsTo links, which is what clients should use to determine what spec the API conforms to, but those links could conceivably contain multiple versions (maybe?) if it conformed to multiple versions.  So having a `stac_api_version` could still be useful I think.

**Comment by geomatician** [comment]
Fixed
