### ISSUE TITLE
pystac-client search returns additional collections

### ISSUE THREAD

**Issue by arthurelmes** [stac-utils/stac-server#259]
When using pystac-client to query a STAC API with version v0.4.0-rc3, the returned items sometimes include additional, non-specified collections. 

Example: searching for `some_collection_id_0.0.1` returns some items with collection id `some_collection_id_0.0.2`.

This may be happening in cases where items were attempted to be ingested by stac-server before their collections had been initialized by a collection template.

**Comment by philvarner** [comment]
CNR. This could happen if the items were created before their collections were created (e.g., the mappings aren't applied to the item indicies), but that has been validated not to be the case.
