### ISSUE TITLE
serverless-pseudo-parameters deprecation warning

### ISSUE THREAD

**Issue by marchuffnagle** [stac-utils/stac-server#273]
When deploying, a deprecation warning is being printed by serverless:

```sh
Serverless: Deprecation warning: "serverless-pseudo-parameters" plugin is no longer needed. Please uninstall it as it will not work with next Framework major release.
            Instead rely on "${aws:region}" and "${aws:accountId}" Serverless Framework variables
```

The documentation for that plugin indicates that it is deprecated as well: https://www.serverless.com/plugins/serverless-pseudo-parameters

From that plugin's readme:

> With version v2.50.0, new variables sources `${aws:accountId}` and `${aws:region}` were introduced, which can be used in properties where CloudFormation pseudo paramaters cannot be used. Please use them instead of `#{AWS::...}` format as supported by this plugin

**Comment by philvarner** [comment]
Fix is to:
- remove all references to serverless-pseudo-parameters
- replace `#{AWS::Region}` with `${aws:region}`, same for accountId
