### ISSUE TITLE
Keyword search enhancement

### ISSUE THREAD

**Issue by hemphillda** [stac-utils/stac-server#29]
Provide an ability to specify a list of keywords on an Item to use in item searching. This allows the item to remain generalized but include indexable/searchable information for specific use cases. For example, an item could be used to represent a parcel, county, contract, easement or land use agreement. 

This is important for applications using STAC to index remote sensing data (e.g., imagery) across a number of vertical markets. I.e., using the same properties schema but allowing arbitrary searchable keywords. 

Usage examples:

3111822110030  (to find an item listing this ID as a keyword)
HEN (to find keywords starting with "Hen")

**Comment by matthewhanson** [comment]
This has been partially added, by adding mappings for text string for text fields like description and titles in this commit:
https://github.com/stac-utils/stac-api/commit/30109526f0066286c1fd0ead598583f5b828e1f4

**Comment by matthewhanson** [comment]
The CQL STAC API extension should cover this.
Implementation covered by #72
