### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#30]
Determine code coverage for tests

Enabling test coverage in AVA https://github.com/avajs/ava/blob/main/docs/recipes/code-coverage.md

**Comment by quetcodesfire** [comment]
It seems as if the issue here is the use of Ava for running tests. It appears that Jest has test coverage built-in and that we're going to be unable to get this information while using Ava.

**Comment by matthewhanson** [comment]
removing from 0.5
