### ISSUE TITLE
Update OpenAPI docs to 1.0.0-rc.1

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#39]
OpenAPI docs seem to be outdated from the latest stac-spec for 0.9.0, need to be updated

openapi-merge seems like a good tool to use to create the spec from those in stac-api-spec
https://www.npmjs.com/package/openapi-merge
https://github.com/robertmassaioli/openapi-merge

**Comment by matthewhanson** [comment]
Pushing to version 0.3.0, which will be compliant with STAC API 1.0.0-beta.1 and has cleaned up OpenAPI docs that can be used.

**Comment by matthewhanson** [comment]
Add service-desc and service-doc links as per https://cmr.uat.earthdata.nasa.gov/stac/MMT_1

**Comment by matthewhanson** [comment]
Copy over latest stac-api-spec OpenAPI doc to libs/api.yaml.

Update info section to reflect `stac-server, license, description, contact, etc.

Update servers section to point to earth-search

**Comment by philvarner** [comment]
```
npm install openapi-merge-cli --save-dev

```

write this to `openapi-merge.json`:

```
{
  "inputs": [
    {
      "inputURL": "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml",
      "append": true
    },
    {
      "inputURL": "https://api.stacspec.org/v1.0.0-beta.5/collections/openapi.yaml",
      "append": true
    },
    {
      "inputURL": "https://api.stacspec.org/v1.0.0-beta.5/ogcapi-features/openapi.yaml",
      "append": true
    },
    {
      "inputURL": "https://api.stacspec.org/v1.0.0-beta.5/ogcapi-features/extensions/transaction/openapi.yaml",
      "append": true
    },
    {
      "inputURL": "https://api.stacspec.org/v1.0.0-beta.5/item-search/openapi.yaml",
      "append": true
    }
  ],
  "output": "./src/lambdas/api/api.yaml"
}
```

run

```
npx openapi-merge-cli
```

But that doesn't work:

```
$ npx openapi-merge-cli
## /Users/philvarner/.nvm/versions/node/v14.19.0/bin/node: Running v1.3.1 (+1ms)
## Loaded the configuration: 5 inputs (+59ms)
## Loading input 0 from URL: https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml (+0ms)
## Loading input 1 from URL: https://api.stacspec.org/v1.0.0-beta.5/collections/openapi.yaml (+16ms)
## Loading input 2 from URL: https://api.stacspec.org/v1.0.0-beta.5/ogcapi-features/openapi.yaml (+2ms)
## Loading input 3 from URL: https://api.stacspec.org/v1.0.0-beta.5/ogcapi-features/extensions/transaction/openapi.yaml (+0ms)
## Loading input 4 from URL: https://api.stacspec.org/v1.0.0-beta.5/item-search/openapi.yaml (+1ms)
## Loaded the inputs into memory, merging the results. (+141ms)
Error merging files: Input 1: The path '/' maps to '/' and this has already been added by another input file (duplicate-paths)
```

**Comment by philvarner** [comment]
The correct approach might be to use yq and then manually edit

```
yq eval-all '. as $item ireduce ({}; . * $item )' core.yaml collections.yaml
```

An open issue is how to get the sort, fields, and query extensions in, since these are only fragments.

**Comment by philvarner** [comment]
May also just want to put this off until after 1.0.0-rc.1 is out so we don't have to do this again soon.

**Comment by matthewhanson** [comment]
We had a process for merging and creating a single yaml at one point, but can't find it in the repo, it might have fallen out during one of the reorgs, but it's here:

https://github.com/radiantearth/stac-api-spec/tree/v0.9.0/api-spec#openapi-definitions

**Comment by philvarner** [comment]
yes, I think I disabled that some point because it was failing. But, now I think I know why -- yq changed between versions 3.x and 4.x from having a `merge` command to having the weird eval thing above.
