### ISSUE TITLE
CORS OPTIONS Preflight Error

### ISSUE THREAD

**Issue by DanSchoppe** [stac-utils/stac-server#498]
👋 Hello,

Thank you to all the contributors to this project. This library and ecosystem is fantastic.

I'm successfully using Element84's Earth Search v1 API to query Sentinel-2 datasets via POST. However, the API doesn't seem to support CORS. An `OPTIONS` request to the `.../search` endpoint results in a 403 status code:

```
$ curl 'https://earth-search.aws.element84.com/v1/search' \
  -X 'OPTIONS' \
  -H 'authority: earth-search.aws.element84.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'access-control-request-headers: content-type' \
  -H 'access-control-request-method: POST' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site'

HTTP/2 403
content-type: application/json
...
{"Message":"User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-west-2:********9419:ug4xl62jti/v1/OPTIONS/search"}%
```

My understanding is that Earth Search v1 is a deployed instance of stac-server, but if not (or if this product feedback is not appropriate for this open source repo) please let me know.

Is this CORS omission intentional? It looks like the intent was for it to be supported:
https://github.com/stac-utils/stac-server/blob/859d2804a80c0ec00d4c974c2851152ee3b13a9c/src/lambdas/api/app.js#L40

... but maybe there's some infrastructure configuration that is incompatible with this Express configuration?

**Comment by philvarner** [comment]
Thanks for bringing this to our attention! The issue was a misconfiguration of the API Gateway, which has now been fixed. Your command worked for me, so please let me know if it's working for you as expected now.

**Comment by DanSchoppe** [comment]
Awesome, thanks @philvarner! The curl posted above is working for me as well.

I'm wrapping something up over the next couple days, then would love to try integrating against the Earth Search v1 API once again to confirm CORS is fully operational. Do you mind if I leave this open until ~mid-next week when I'll be able to test this more thoroughly?

Thanks so much for the fix.

**Comment by DanSchoppe** [comment]
@philvarner Finally got around to testing this, and CORS works well! Thanks again!
