### ISSUE TITLE
how to crawl and ingest STAC data from S3 location.

### ISSUE THREAD

**Issue by drzhouq** [stac-utils/stac-server#534]
After reading the documentation, I am still not sure how I implement my own STAC server and populate the STAC server with content from s3://usgs-landsat/collection02/level-1/ recursively? Do I have to recursively get all the catalog.json *_stac.json from the bucket and prefix, create sqs messages point the location? @philvarner 

many thanks for your help.

**Comment by philvarner** [comment]
That's correct.
