### ISSUE TITLE
links is not defined

### ISSUE THREAD

**Issue by aliasmrchips** [stac-utils/stac-server#58]
I am seeing a ReferenceError when results need to be paged. Maybe coming from here?

https://github.com/stac-utils/stac-server/blob/008f49f800023514793a97f19ea12a3c707214e1/libs/api.js#L327

Should this be `link` (defined on line 317) not `links`?

**Comment by matthewhanson** [comment]
Fixed in 0.2.1

**Comment by matthewhanson** [comment]
@aliasmrchips this has been deployed to earth-search
