### ISSUE TITLE
Update sorting to align with OGC API

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#74]
https://github.com/radiantearth/stac-api-spec/issues/16

**Comment by matthewhanson** [comment]
Check sorting logic here https://github.com/stac-utils/stac-server/blob/main/libs/es.js#L158 against spec here: https://github.com/radiantearth/stac-api-spec/tree/master/fragments/sort

**Comment by demiurg** [comment]
Oh, is this something you did? I didn't look at sorting.

**Comment by matthewhanson** [comment]
It was already compliant, since OGC Features changed their spec to align with STAC. I validated it works as expected.
