### ISSUE TITLE
Geometry in next/prev GET links not being serialized

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#85]
Bug report from an email.

***
This search returns a JSON:

https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00:00:00.000Z/2020-08-16T00:00:00.000Z&bbox=[137.772897,0.0,153.749135,60.0]&collections=[%22sentinel-s2-l1c%22]&limit=2&page=1

The link to the next page ('$.links[?(@.rel="next")].href') in the JSON is as follows:

https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00%3A00%3A00.000Z%2F2020-08-16T00%3A00%3A00.000Z&intersects=%5Bobject%20Object%5D&collections[]=sentinel-s2-l1c&page=2&limit=2

As it can be observed, the link to the next page doesn't have a proper definition for the geometry searc, the bbox has been turned into an intersects with an ill-defined value.

**Comment by matthewhanson** [comment]
Deployed to test.

https://un81fxtdxh.execute-api.us-west-2.amazonaws.com/v1/search?datetime=2021-01-01T00:00:00.000Z/2021-07-01T00:00:00.000Z&bbox=%5B120,0.0,130,60.0%5D&collections=%5B%22sentinel-s2-l2a-cogs%22%5D

has a next link that returns `search_phase_execution_exception`.

There's a couple unrelated issues here:
1 - The bbox parameter is getting transformed into an intersects query on the next page. This is because the extractBBox function converts bbox into an intersects geometry: https://github.com/stac-utils/stac-server/blob/main/libs/api.js#L46
2 - An intersects param converted to a GET request seems to fail.  Not sure if this is due to the pagination logic, or a larger problem with parsing geometries in GET requests.  Recommend to first find an intersects query that works with a GET request, and see if the problem is there. Then, look at pagination.

**Comment by demiurg** [comment]
I agree on #2, it should work, and I have a test where it seems to work. Will look at it. For #1, it seemed like it was a lesser priority, but I agree it would be cleaner to re-use whatever the original argument is.

**Comment by matthewhanson** [comment]
Agree that first one is lesser priority, opened up #99 for that. This issue should just handle the intersects issue
