### ISSUE TITLE
Evaluate testing process

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/stac-server#90]
Evaluate current testing approach and libraries, recommend changes

**Comment by demiurg** [comment]
Based on my current experience, the next best thing would be to understand how to make the integration tests automatically. Right now, I run three separate commands, which works manually:

1. Start docker compose, call aws command compatible with localstack to install ES
2. Import fixtures
3. Run integration tests

The ava tests are fine, there are a few issues.

1. integration tests are calling API object directly, not testing lambda or api GW functionality
2. the test process is manual

localstack is capable of running api gateway, we need to extend the approach to deploy the lambdas locally and tests can be modified to call it.

Next, there should be a way to automate the process, and launch the tests inside a container, as well as to cache the localstack installed state between multiple test runs.

**Comment by matthewhanson** [comment]
@demiurg when you get a chance can you open up issues for the recommendations, then we can close this one

**Comment by demiurg** [comment]
Will do!

**Comment by demiurg** [comment]
https://github.com/stac-utils/stac-server/issues/97
https://github.com/stac-utils/stac-server/issues/98
